### PR TITLE
fix: avoid act warnings

### LINKED ISSUE #37: Act warnings in Vitest Browser Mode
After upgrading from Vitest 3 to Vitest 4.0.0 (and upgrading vitest-browser-react from ^1.0.0 to ^2.0.0) I'm suddenly getting "act" warnings in my tests. Am I correct in thinking that when running tests in browser mode, it doesn't make sense to see any messages about "act"?

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #37

### CODE REVIEW

File: src/pure.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ function ensureTestIdAttribute(element: HTMLElement) {
 let activeActs = 0
 
 function setActEnvironment(env: boolean | undefined): void {
-  (globalThis as any).IS_REACT_ACT_ENVIRONMENT = env
+  ;(globalThis as any).IS_REACT_ACT_ENVIRONMENT = env
```
Comment (wojtekmaj) [inline src/pure.tsx]: Is that intentional? Looks a bit weird, but maybe I don't know something? If so, I'd love to learn!
